const GAS_FEE = 0.0001;
MAX_FEE = 0.001;
const COMPLEXITY_MULTIPLIER = 0.01; 
const TOKEN_CREATION_FEE = 0.05
const NFT_CREATION_FEE = 0.01

module.exports = {
    GAS_FEE,
    MAX_FEE,
    COMPLEXITY_MULTIPLIER,
    TOKEN_CREATION_FEE,
    NFT_CREATION_FEE
}